'use strict';

/*
 * ONE SKILL, ONE NAME (2026-09-29).
 *
 * Measured before: four copies, three names (coderifts / api-governance / coderifts-api-governance),
 * three bodies. Now the three plugin carriers carry one body byte for byte (the union — generated by
 * coderifts-app scripts/generate-skill-carriers.js from agent/skills/coderifts/SKILL.md) and the
 * same `name: coderifts`; only the frontmatter `description` differs per host.
 *
 * The website half: the website publishes the Cursor carrier at .well-known/agent-skills/coderifts/
 * and its index.json carries a digest of the served bytes (the website's own
 * check-agent-skills-digest guard proves index ↔ served). This test adds the missing link: served ↔
 * this repository. It runs when a website checkout is present (CODERIFTS_WEBSITE_DIR, or
 * ~/coderifts-website) and SAYS it did not run otherwise.
 */

const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const CARRIERS = Object.freeze({
  claude: 'plugins/api-governance/skills/api-governance/SKILL.md',
  cursor: 'plugins/api-governance-cursor/skills/coderifts/SKILL.md',
  codex: 'plugins/api-governance-openai/skills/api-governance/SKILL.md',
});
const NAME = 'coderifts';

const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
function split(text) {
  assert.ok(text.startsWith('---\n'), 'frontmatter must open on line 1');
  const end = text.indexOf('\n---', 4);
  assert.ok(end > 0, 'frontmatter must close');
  return { fm: text.slice(4, end), body: text.slice(end + 4) };
}
const sha = (buf) => `sha256:${crypto.createHash('sha256').update(buf).digest('hex')}`;

test('⚠⚠ the three plugin carriers carry one body, byte for byte', () => {
  const bodies = Object.entries(CARRIERS).map(([id, rel]) => [id, split(read(rel)).body]);
  const [first, ...rest] = bodies;
  for (const [id, body] of rest) {
    assert.equal(body, first[1], `${id} body differs from ${first[0]} — regenerate with coderifts-app scripts/generate-skill-carriers.js`);
  }
});

test('⚠⚠ every carrier is named coderifts', () => {
  for (const [id, rel] of Object.entries(CARRIERS)) {
    const m = /^name:\s*(.+?)\s*$/m.exec(split(read(rel)).fm);
    assert.ok(m, `${id} has no name`);
    assert.equal(m[1], NAME, `${id} is named ${m[1]}`);
  }
});

test('no carrier survives under an old skill directory name', () => {
  assert.ok(!fs.existsSync(path.join(ROOT, 'plugins/api-governance-cursor/skills/coderifts-api-governance')));
});

const WEBSITE = process.env.CODERIFTS_WEBSITE_DIR || path.join(os.homedir(), 'coderifts-website');
const served = path.join(WEBSITE, '.well-known', 'agent-skills', NAME, 'SKILL.md');
const index = path.join(WEBSITE, '.well-known', 'agent-skills', 'index.json');
const haveWebsite = fs.existsSync(served) && fs.existsSync(index);

test('⚠ the website serves the Cursor carrier, and its index digest is this repository\'s bytes',
  { skip: haveWebsite ? false : `website checkout without .well-known/agent-skills/${NAME}/ at ${WEBSITE} — NOT RUN` }, () => {
    const mine = fs.readFileSync(path.join(ROOT, CARRIERS.cursor));
    assert.equal(sha(fs.readFileSync(served)), sha(mine), 'served SKILL.md is not the Cursor carrier');
    const entry = (JSON.parse(fs.readFileSync(index, 'utf8')).skills || []).find((s) => s.name === NAME);
    assert.ok(entry, `index.json has no ${NAME} entry`);
    assert.equal(entry.digest, sha(mine), 'index.json digest is not the Cursor carrier digest');
    assert.equal(entry.url, `/.well-known/agent-skills/${NAME}/SKILL.md`);
  });
